---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-access-antware-xyz-v1alpha1-jitaccessrequest
  failurePolicy: Fail
  name: mjitaccessrequest-v1alpha1.kb.io
  rules:
  - apiGroups:
    - access.antware.xyz
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jitaccessrequests
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-access-antware-xyz-v1alpha1-jitaccessrequest
  failurePolicy: Fail
  name: vjitaccessrequest-v1alpha1.kb.io
  rules:
  - apiGroups:
    - access.antware.xyz
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jitaccessrequests
  sideEffects: None
