# This rule is not used by the project jitaccess itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over access.antware.xyz.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jitaccess
    app.kubernetes.io/managed-by: kustomize
  name: accessrequest-admin-role
rules:
- apiGroups:
  - access.antware.xyz
  resources:
  - accessrequests
  verbs:
  - '*'
- apiGroups:
  - access.antware.xyz
  resources:
  - accessrequests/status
  verbs:
  - get
