apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jitaccess
    app.kubernetes.io/managed-by: kustomize
  name: jitaccessrequest-requester-role
rules:
- apiGroups:
  - access.antware.xyz
  resources:
  - jitaccessrequests
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - access.antware.xyz
  resources:
  - jitaccessrequests/status
  verbs:
  - get
