# This rule is not used by the project jitaccess itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the access.antware.xyz.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jitaccess
    app.kubernetes.io/managed-by: kustomize
  name: jitaccessrequest-editor-role
rules:
- apiGroups:
  - access.antware.xyz
  resources:
  - jitaccessrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.antware.xyz
  resources:
  - jitaccessrequests/status
  verbs:
  - get
