{
 "title": "Just-in-time Access",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Top Subjects",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jitaccess_roles_granted) by (subject)",
     "legendFormat": "{{subject}}"
    }
   ]
  },
  {
   "title": "Top Roles",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jitaccess_roles_granted) by (roleKind,role)",
     "legendFormat": "{{roleKind}}/{{role}}"
    }
   ]
  },
  {
   "title": "Top Permissions",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n    label_join(\n        label_replace(\n            sum(jitaccess_permissions_granted) by (apiGroup,resource,verb,resourceName),\n                \"resourceName\", \"*\", \"resourceName\", \"^$\"\n        ),\n        \"permission\", \"/\", \"verb\", \"apiGroup\", \"resource\", \"resourceName\"\n    ),\n    \"permission\", \"$1/$2\", \"permission\", \"(.+)//(.+)\"\n)",
     "legendFormat": "{{permission}}"
    }
   ]
  },
  {
   "title": "Average Duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jitaccess_grant_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Reconcile Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(controller_runtime_reconcile_time_seconds_sum{namespace=\"jit-access-system\"} / controller_runtime_reconcile_time_seconds_count{namespace=\"jit-access-system\"})",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Current Requests",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(jitaccess_request_status == 0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "count(jitaccess_request_status == 1)",
     "legendFormat": "Approved"
    },
    {
     "expr": "count(jitaccess_request_status == 2)",
     "legendFormat": "Denied"
    }
   ]
  },
  {
   "title": "Current Requests",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "expr": "sum(jitaccess_request_status) by (request, scope, target_namespace, subject)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}