apiVersion: access.antware.xyz/v1alpha1
kind: ClusterJITAccessPolicy
metadata:
  labels:
    app.kubernetes.io/name: jitaccess
    app.kubernetes.io/managed-by: kustomize
  name: clusterjitaccesspolicy-sample
spec:
  # TODO(user): Add fields here
