apiVersion: access.antware.xyz/v1alpha1
kind: JITAccessRequest
metadata:
  labels:
    app.kubernetes.io/name: jitaccess
    app.kubernetes.io/managed-by: kustomize
  name: jitaccessrequest-sample
spec:
  subject: alice@example.com
  role: view
  durationSeconds: 300