apiVersion: access.antware.xyz/v1alpha1
kind: ClusterJITAccessPolicy
metadata:
  labels:
    app.kubernetes.io/name: jitaccess
    app.kubernetes.io/managed-by: kustomize
  name: clusterjitaccesspolicy-sample
spec:
  policies:
    - subject: alice@example.com
      allowedClusterRoles:
        - view
        - dev-debug
      maxDurationSeconds: 1800
    - subject: bob@example.com
      allowedClusterRoles:
        - readonly
      maxDurationSeconds: 600