apiVersion: access.antware.xyz/v1alpha1
kind: JITAccessPolicy
metadata:
  labels:
    app.kubernetes.io/name: jitaccess
    app.kubernetes.io/managed-by: kustomize
  name: jitaccesspolicy-sample
spec:
  policies:
    - subjects:
        - alice@example.com
      allowedRoles:
        - view
        - dev-debug
      allowedPermissions:
        - apiGroups: [""]
          resources: ["pods"]
          verbs: ["get", "list", "watch"]
      maxDurationSeconds: 1800
      requiredApprovals: 1
      approvers:
        - admin
    - subjects:
        - bob@example.com
      allowedRoles:
        - readonly
      maxDurationSeconds: 600
      requiredApprovals: 2
      approvers:
        - admin
        - alice@example.com