---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: approver-role
rules:
- apiGroups:
  - access.antware.xyz
  resources:
  - clusterjitaccessrequests
  - jitaccessrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - access.antware.xyz
  resources:
  - clusterjitaccessrequests/status
  - jitaccessrequests/status
  verbs:
  - get
  - patch
  - update