apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jitaccess
    app.kubernetes.io/component: approval-server
    app.kubernetes.io/managed-by: kustomize
  name: approval-server-service
  namespace: system
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: jitaccess
    app.kubernetes.io/component: approval-server
