name: Publish Helm Chart

on:
  workflow_run:
    workflows: ["Test Chart"]
    types:
      - completed

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.FILE_SYNC_PAT }}
          IS_FINE_GRAINED: true
          PR_LABELS: |
            file-sync
            automerge